### PR TITLE
room frontend: fetch question and add code editor to room

### PR DESCRIPTION
**Pull request by vivienherq**
## Description

updated frontend for room 

## Type of Change

- [ ] Bug fix
- [x] New feature
- [x] Improvement
- [ ] Documentation update

## Screenshots (if applicable)

Screenshot 2024-10-19 at 10 01 27 PM

### CODE REVIEW

**Comment by joulev** [comment]
Thanks!

It's worth noting that I have a rough working example of a collaborative Monaco editor [here](https://github.com/CS3219-AY2425S1/cs3219-ay2425s1-project-g37/tree/joulev/ws) when I played with YJS a few weeks ago, so we can integrate that with the frontend here to have a working collaborative editor running.

**Comment by vivienherq** [comment]
> Thanks!
> 
> It's worth noting that I have a rough working example of a collaborative Monaco editor [here](https://github.com/CS3219-AY2425S1/cs3219-ay2425s1-project-g37/tree/joulev/ws) when I played with YJS a few weeks ago, so we can integrate that with the frontend here to have a working collaborative editor running.

thanks! i integrated it into the frontend, might need your help to set up the collab service backend 😭

**Comment by joulev** [comment]
Yeah the collaborative part is on the backend so the frontend needs not do much about it, I think you should even remove the YJS part from the frontend from here as the backend is not running yet. But yeah that branch will give us an overview of what the backend and the connection will look like.

By the way, I had been thinking about the code execution part, as that is not a requirement and running user code is a PITA so we might just ditch that feature. In that case the frontend will look something like this

image

image

and the submit on Leetcode button is simply a link to open the Leetcode page.

**Comment by vivienherq** [comment]
> Yeah the collaborative part is on the backend so the frontend needs not do much about it, I think you should even remove the YJS part from the frontend from here as the backend is not running yet. But yeah that branch will give us an overview of what the backend and the connection will look like.
> 
> By the way, I had been thinking about the code execution part, as that is not a requirement and running user code is a PITA so we might just ditch that feature. In that case the frontend will look something like this
> 
> image
> 
> image
> 
> and the submit on Leetcode button is simply a link to open the Leetcode page.

in that case, would we need to come up with another Nice-To-Have ... 🙂 i do agree that it will be quite a pain tho 😂

**Comment by joulev** [comment]
@vivienherq I just pushed the backend, there are some conflicts so I'm afraid you have to resolve them.

Also might be a good idea to add the navbar in the UI prototype as well. It's not possible with the existing `auth-protected.tsx` layout so a new layout specifically for room pages is needed.

Also I installed the necessary dependencies into `apps/peerprep/package.json`, so might be a good idea also to not install them in the root `package.json`.

**Comment by joulev** [comment]
Nvm I am quite free today so I resolved the conflict and fixed the UI a bit to fit the prototype more.

**Review by joulev — APPROVED** [review]
Good to go, thanks!

**Pull request merged**
