### PR TITLE
ai service

### PR DESCRIPTION
**Pull request by vivienherq**
## Description

allow user to communicate with ai chatbot 

## Type of Change

- [ ] Bug fix
- [x] New feature
- [x] Improvement
- [ ] Documentation update

## Screenshots (if applicable)

Screenshot 2024-10-28 at 10 32 02 PM

update: chat is now shared & persisted in ai chat room
Screenshot 2024-10-31 at 3 27 46 PM

## Additional Notes

- i need some help with the calling of the api... like the swr part 😅

### CODE REVIEW

**Comment by joulev** [comment]
Hmm I was thinking to allow AI inside the chat room itself, something like this:

* User sends a message containing `@ai` for example
* As the user sends that, we also send a stateless message, something like `{ type: "ai", prompt: "the message" }`
* Server (collab service) detects that stateless message, runs AI and returns the result by appending a chat message to the server-side document.

In that case we automatically share AI output to both users and the output is automatically persisted as well (the document is saved in the database).

Do you think we should have the AI chat separate (and hidden from collaborator) or shared inside the chat room with the collaborator?

**Comment by vivienherq** [comment]
> Hmm I was thinking to allow AI inside the chat room itself, something like this:
> 
> * User sends a message containing `@ai` for example
> * As the user sends that, we also send a stateless message, something like `{ type: "ai", prompt: "the message" }`
> * Server (collab service) detects that stateless message, runs AI and returns the result by appending a chat message to the server-side document.
> 
> In that case we automatically share AI output to both users and the output is automatically persisted as well (the document is saved in the database).
> 
> Do you think we should have the AI chat separate (and hidden from collaborator) or shared inside the chat room with the collaborator?

hmm, i thought separate made sense because one user may want a hint when the other user doesn't (so maybe not in the main chat room).. but the ai chat room could be shared with the other user, then that user could still choose whether or not they want to see the hints given?

**Comment by joulev** [comment]
Yeah, that sounds good to me actually. That's a great idea, a Discord server I'm in also implements something like that.

**Review by joulev — APPROVED** [review]
I made a few changes to make the bot remember the context of the conversation, but otherwise we are good to go now. Thanks!

image

**Pull request merged**
